//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace keybon.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string portName {
            get {
                return ((string)(this["portName"]));
            }
            set {
                this["portName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::keybon.ScreenLayout Layout1 {
            get {
                return ((global::keybon.ScreenLayout)(this["Layout1"]));
            }
            set {
                this["Layout1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::keybon.ScreenLayout Layout2 {
            get {
                return ((global::keybon.ScreenLayout)(this["Layout2"]));
            }
            set {
                this["Layout2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::keybon.ScreenLayout Layout3 {
            get {
                return ((global::keybon.ScreenLayout)(this["Layout3"]));
            }
            set {
                this["Layout3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::keybon.ScreenLayout Layout4 {
            get {
                return ((global::keybon.ScreenLayout)(this["Layout4"]));
            }
            set {
                this["Layout4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::keybon.ScreenLayout Layout5 {
            get {
                return ((global::keybon.ScreenLayout)(this["Layout5"]));
            }
            set {
                this["Layout5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::keybon.ScreenLayout Layout6 {
            get {
                return ((global::keybon.ScreenLayout)(this["Layout6"]));
            }
            set {
                this["Layout6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::keybon.ScreenLayout Layout7 {
            get {
                return ((global::keybon.ScreenLayout)(this["Layout7"]));
            }
            set {
                this["Layout7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::keybon.ScreenLayout Layout8 {
            get {
                return ((global::keybon.ScreenLayout)(this["Layout8"]));
            }
            set {
                this["Layout8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::keybon.ScreenLayout Layout9 {
            get {
                return ((global::keybon.ScreenLayout)(this["Layout9"]));
            }
            set {
                this["Layout9"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::keybon.ScreenLayout Layout10 {
            get {
                return ((global::keybon.ScreenLayout)(this["Layout10"]));
            }
            set {
                this["Layout10"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::keybon.ScreenLayout Layout11 {
            get {
                return ((global::keybon.ScreenLayout)(this["Layout11"]));
            }
            set {
                this["Layout11"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::keybon.ScreenLayout Layout12 {
            get {
                return ((global::keybon.ScreenLayout)(this["Layout12"]));
            }
            set {
                this["Layout12"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::keybon.ScreenLayout Layout13 {
            get {
                return ((global::keybon.ScreenLayout)(this["Layout13"]));
            }
            set {
                this["Layout13"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::keybon.ScreenLayout Layout14 {
            get {
                return ((global::keybon.ScreenLayout)(this["Layout14"]));
            }
            set {
                this["Layout14"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::keybon.ScreenLayout Layout15 {
            get {
                return ((global::keybon.ScreenLayout)(this["Layout15"]));
            }
            set {
                this["Layout15"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool checkedBox1 {
            get {
                return ((bool)(this["checkedBox1"]));
            }
            set {
                this["checkedBox1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool checkedBox2 {
            get {
                return ((bool)(this["checkedBox2"]));
            }
            set {
                this["checkedBox2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool checkedBox3 {
            get {
                return ((bool)(this["checkedBox3"]));
            }
            set {
                this["checkedBox3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool checkedBox4 {
            get {
                return ((bool)(this["checkedBox4"]));
            }
            set {
                this["checkedBox4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool checkedBox5 {
            get {
                return ((bool)(this["checkedBox5"]));
            }
            set {
                this["checkedBox5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool checkedBox6 {
            get {
                return ((bool)(this["checkedBox6"]));
            }
            set {
                this["checkedBox6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool checkedBox7 {
            get {
                return ((bool)(this["checkedBox7"]));
            }
            set {
                this["checkedBox7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool checkedBox8 {
            get {
                return ((bool)(this["checkedBox8"]));
            }
            set {
                this["checkedBox8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool checkedBox9 {
            get {
                return ((bool)(this["checkedBox9"]));
            }
            set {
                this["checkedBox9"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool checkedBox10 {
            get {
                return ((bool)(this["checkedBox10"]));
            }
            set {
                this["checkedBox10"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool checkedBox11 {
            get {
                return ((bool)(this["checkedBox11"]));
            }
            set {
                this["checkedBox11"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool checkedBox12 {
            get {
                return ((bool)(this["checkedBox12"]));
            }
            set {
                this["checkedBox12"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool checkedBox13 {
            get {
                return ((bool)(this["checkedBox13"]));
            }
            set {
                this["checkedBox13"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool checkedBox14 {
            get {
                return ((bool)(this["checkedBox14"]));
            }
            set {
                this["checkedBox14"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool checkedBox15 {
            get {
                return ((bool)(this["checkedBox15"]));
            }
            set {
                this["checkedBox15"] = value;
            }
        }
    }
}
