//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace keybon.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string portName {
            get {
                return ((string)(this["portName"]));
            }
            set {
                this["portName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::keybon.ScreenLayout Layout1 {
            get {
                return ((global::keybon.ScreenLayout)(this["Layout1"]));
            }
            set {
                this["Layout1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::keybon.ScreenLayout Layout2 {
            get {
                return ((global::keybon.ScreenLayout)(this["Layout2"]));
            }
            set {
                this["Layout2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::keybon.ScreenLayout Layout3 {
            get {
                return ((global::keybon.ScreenLayout)(this["Layout3"]));
            }
            set {
                this["Layout3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::keybon.ScreenLayout Layout4 {
            get {
                return ((global::keybon.ScreenLayout)(this["Layout4"]));
            }
            set {
                this["Layout4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::keybon.ScreenLayout Layout5 {
            get {
                return ((global::keybon.ScreenLayout)(this["Layout5"]));
            }
            set {
                this["Layout5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::keybon.ScreenLayout Layout6 {
            get {
                return ((global::keybon.ScreenLayout)(this["Layout6"]));
            }
            set {
                this["Layout6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::keybon.ScreenLayout Layout7 {
            get {
                return ((global::keybon.ScreenLayout)(this["Layout7"]));
            }
            set {
                this["Layout7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::keybon.ScreenLayout Layout8 {
            get {
                return ((global::keybon.ScreenLayout)(this["Layout8"]));
            }
            set {
                this["Layout8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::keybon.ScreenLayout Layout9 {
            get {
                return ((global::keybon.ScreenLayout)(this["Layout9"]));
            }
            set {
                this["Layout9"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::keybon.ScreenLayout Layout10 {
            get {
                return ((global::keybon.ScreenLayout)(this["Layout10"]));
            }
            set {
                this["Layout10"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::keybon.ScreenLayout Layout11 {
            get {
                return ((global::keybon.ScreenLayout)(this["Layout11"]));
            }
            set {
                this["Layout11"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::keybon.ScreenLayout Layout12 {
            get {
                return ((global::keybon.ScreenLayout)(this["Layout12"]));
            }
            set {
                this["Layout12"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::keybon.ScreenLayout Layout13 {
            get {
                return ((global::keybon.ScreenLayout)(this["Layout13"]));
            }
            set {
                this["Layout13"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::keybon.ScreenLayout Layout14 {
            get {
                return ((global::keybon.ScreenLayout)(this["Layout14"]));
            }
            set {
                this["Layout14"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::keybon.ScreenLayout Layout15 {
            get {
                return ((global::keybon.ScreenLayout)(this["Layout15"]));
            }
            set {
                this["Layout15"] = value;
            }
        }
    }
}
